name: HubLobbySelector
version: 1.0
author: Killer5252
main: me.McKiller5252.lobbyselector.LobbySelector
description: Allows you to teleport to diffrent lobbies.
commands:
   ls:
      description: This will give you the LobbySelector
      usage: /ls
      permission: LobbySelector.ls
      permission-message: You don't have permission to use this command.
      
permissions:
   LobbySelector.*:
    children:
      LobbySelector.builder: true
      LobbySelector.architect: true
    LobbySelector.builder:
       default: true
    LobbySelector.architect:
       default: true